version: "3"

services:
  backend:
    env_file: "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "dani/cartrack-asignment-backend"
    ports:
      - "8080:8080"
    volumes:
        - ./backend:/api
        - /backend/node_modules
  frontend:
    env_file: "./frontend/.env"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "dani/cartrack-asignment-front"
    ports:
      - "3000:3000"
    links:
      - "backend"
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'
